export const keyEvents = {
  0: {
    enKey: '`',
    enKeyShift: '~',
    ruKeyShift: 'Ё',
    ruKey: 'ё',
    enKeyCaps: '`',
    ruKeyCaps: 'Ё',
    id: 0,
  },
  1: {
    enKey: '1',
    enKeyShift: '!',
    ruKeyShift: '!',
    ruKey: '1',
    enKeyCaps: '1',
    ruKeyCaps: '1',
    id: 1,
  },
  2: {
    enKey: '2',
    enKeyShift: '@',
    ruKeyShift: '"',
    ruKey: '2',
    enKeyCaps: '2',
    ruKeyCaps: '2',
    id: 2,
  },
  3: {
    enKey: '3',
    enKeyShift: '#',
    ruKeyShift: '№',
    ruKey: '3',
    enKeyCaps: '3',
    ruKeyCaps: '3',
    id: 3,
  },
  4: {
    enKey: '4',
    enKeyShift: '$',
    ruKeyShift: ';',
    ruKey: '4',
    enKeyCaps: '4',
    ruKeyCaps: '4',
    id: 4,
  },
  5: {
    enKey: '5',
    enKeyShift: '%',
    ruKeyShift: '%',
    ruKey: '5',
    enKeyCaps: '5',
    ruKeyCaps: '5',
    id: 5,
  },
  6: {
    enKey: '6',
    enKeyShift: '^',
    ruKeyShift: ':',
    ruKey: '6',
    enKeyCaps: '6',
    ruKeyCaps: '6',
    id: 6,
  },
  7: {
    enKey: '7',
    enKeyShift: '&',
    ruKeyShift: '?',
    ruKey: '7',
    enKeyCaps: '7',
    ruKeyCaps: '7',
    id: 7,
  },
  8: {
    enKey: '8',
    enKeyShift: '*',
    ruKeyShift: '*',
    ruKey: '8',
    enKeyCaps: '8',
    ruKeyCaps: '8',
    id: 8,
  },
  9: {
    enKey: '9',
    enKeyShift: '(',
    ruKeyShift: '(',
    ruKey: '9',
    enKeyCaps: '9',
    ruKeyCaps: '9',
    id: 9,
  },
  10: {
    enKey: '0',
    enKeyShift: ')',
    ruKeyShift: ')',
    ruKey: '0',
    enKeyCaps: '0',
    ruKeyCaps: '0',
    id: 10,
  },
  11: {
    enKey: '-',
    enKeyShift: '_',
    ruKeyShift: '_',
    ruKey: '-',
    enKeyCaps: '-',
    ruKeyCaps: '-',
    id: 11,
  },
  12: {
    enKey: '=',
    enKeyShift: '+',
    ruKeyShift: '+',
    ruKey: '=',
    enKeyCaps: '=',
    ruKeyCaps: '=',
    id: 12,
  },
  13: {
    enKey: 'Backspace',
    enKeyCaps: 'Backspace',
    id: 13,
    style: 'static_big',
  },
  14: {
    enKey: 'Tab',
    id: 14,
    style: 'static_tab',
  },
  15: {
    enKey: 'q',
    enKeyShift: 'Q',
    ruKeyShift: 'Й',
    ruKey: 'й',
    enKeyCaps: 'Q',
    ruKeyCaps: 'Й',
    id: 15,
  },
  16: {
    enKey: 'w',
    enKeyShift: 'W',
    ruKeyShift: 'Ц',
    ruKey: 'ц',
    enKeyCaps: 'W',
    ruKeyCaps: 'Ц',
    id: 16,
  },
  17: {
    enKey: 'e',
    enKeyShift: 'E',
    ruKeyShift: 'У',
    ruKey: 'у',
    enKeyCaps: 'E',
    ruKeyCaps: 'У',
    id: 17,
  },
  18: {
    enKey: 'r',
    enKeyShift: 'R',
    ruKeyShift: 'К',
    ruKey: 'к',
    enKeyCaps: 'R',
    ruKeyCaps: 'К',
    id: 18,
  },
  19: {
    enKey: 't',
    enKeyShift: 'T',
    ruKeyShift: 'Е',
    ruKey: 'е',
    enKeyCaps: 'T',
    ruKeyCaps: 'Е',
    id: 19,
  },
  20: {
    enKey: 'y',
    enKeyShift: 'Y',
    ruKeyShift: 'Н',
    ruKey: 'н',
    enKeyCaps: 'Y',
    ruKeyCaps: 'Н',
    id: 20,
  },
  21: {
    enKey: 'u',
    enKeyShift: 'U',
    ruKeyShift: 'Г',
    ruKey: 'г',
    enKeyCaps: 'U',
    ruKeyCaps: 'Г',
    id: 21,
  },
  22: {
    enKey: 'i',
    enKeyShift: 'I',
    ruKeyShift: 'Ш',
    ruKey: 'ш',
    enKeyCaps: 'I',
    ruKeyCaps: 'Ш',
    id: 22,
  },
  23: {
    enKey: 'o',
    enKeyShift: 'O',
    ruKeyShift: 'Щ',
    ruKey: 'щ',
    enKeyCaps: 'O',
    ruKeyCaps: 'Щ',
    id: 23,
  },
  24: {
    enKey: 'p',
    enKeyShift: 'P',
    ruKeyShift: 'З',
    ruKey: 'з',
    enKeyCaps: 'P',
    ruKeyCaps: 'З',
    id: 24,
  },
  25: {
    enKey: '[',
    enKeyShift: '{',
    ruKeyShift: 'Х',
    ruKey: 'х',
    enKeyCaps: '[',
    ruKeyCaps: 'Х',
    id: 25,
  },
  26: {
    enKey: ']',
    enKeyShift: '}',
    ruKeyShift: 'Ъ',
    ruKey: 'ъ',
    enKeyCaps: ']',
    ruKeyCaps: 'Ъ',
    id: 26,
  },
  27: {
    enKey: '\\',
    enKeyShift: '|',
    ruKeyShift: '/',
    ruKey: '\\',
    enKeyCaps: '\\',
    ruKeyCaps: '\\',
    id: 27,
  },
  28: {
    enKey: 'Del',
    id: 28,
    style: 'static',
  },
  29: {
    enKey: 'CapsLock',
    id: 29,
    style: 'static_big',
  },
  30: {
    enKey: 'a',
    enKeyShift: 'A',
    ruKeyShift: 'Ф',
    ruKey: 'ф',
    enKeyCaps: 'A',
    ruKeyCaps: 'Ф',
    id: 30,
  },
  31: {
    enKey: 's',
    enKeyShift: 'S',
    ruKeyShift: 'Ы',
    ruKey: 'ы',
    enKeyCaps: 'S',
    ruKeyCaps: 'Ы',
    id: 31,
  },
  32: {
    enKey: 'd',
    enKeyShift: 'D',
    ruKeyShift: 'В',
    ruKey: 'в',
    enKeyCaps: 'D',
    ruKeyCaps: 'В',
    id: 32,
  },
  33: {
    enKey: 'f',
    enKeyShift: 'F',
    ruKeyShift: 'А',
    ruKey: 'а',
    enKeyCaps: 'F',
    ruKeyCaps: 'А',
    id: 33,
  },
  34: {
    enKey: 'g',
    enKeyShift: 'G',
    ruKeyShift: 'П',
    ruKey: 'п',
    enKeyCaps: 'G',
    ruKeyCaps: 'П',
    id: 34,
  },
  35: {
    enKey: 'h',
    enKeyShift: 'H',
    ruKeyShift: 'Р',
    ruKey: 'р',
    enKeyCaps: 'H',
    ruKeyCaps: 'Р',
    id: 35,
  },
  36: {
    enKey: 'j',
    enKeyShift: 'J',
    ruKeyShift: 'О',
    ruKey: 'о',
    enKeyCaps: 'J',
    ruKeyCaps: 'О',
    id: 36,
  },
  37: {
    enKey: 'k',
    enKeyShift: 'K',
    ruKeyShift: 'Л',
    ruKey: 'л',
    enKeyCaps: 'K',
    ruKeyCaps: 'Л',
    id: 37,
  },
  38: {
    enKey: 'l',
    enKeyShift: 'L',
    ruKeyShift: 'Д',
    ruKey: 'д',
    enKeyCaps: 'L',
    ruKeyCaps: 'Д',
    id: 38,
  },
  39: {
    enKey: ';',
    enKeyShift: ':',
    ruKeyShift: 'Ж',
    ruKey: 'ж',
    enKeyCaps: ';',
    ruKeyCaps: 'Ж',
    id: 39,
  },
  40: {
    enKey: `'`,
    enKeyShift: `"`,
    ruKeyShift: 'Э',
    ruKey: 'э',
    enKeyCaps: `'`,
    ruKeyCaps: 'Э',
    id: 40,
  },
  41: {
    enKey: 'Enter',
    id: 41,
    style: 'static_mid',
  },
  42: {
    enKey: 'Shift',
    id: 42,
    style: 'static_big',
  },
  43: {
    enKey: 'z',
    enKeyShift: 'Z',
    ruKeyShift: 'Я',
    ruKey: 'я',
    enKeyCaps: 'Z',
    ruKeyCaps: 'Я',
    id: 43,
  },
  44: {
    enKey: 'x',
    enKeyShift: 'X',
    ruKeyShift: 'Ч',
    ruKey: 'ч',
    enKeyCaps: 'X',
    ruKeyCaps: 'Ч',
    id: 44,
  },
  45: {
    enKey: 'c',
    enKeyShift: 'C',
    ruKeyShift: 'С',
    ruKey: 'с',
    enKeyCaps: 'C',
    ruKeyCaps: 'С',
    id: 45,
  },
  46: {
    enKey: 'v',
    enKeyShift: 'V',
    ruKeyShift: 'М',
    ruKey: 'м',
    enKeyCaps: 'V',
    ruKeyCaps: 'М',
    id: 46,
  },
  47: {
    enKey: 'b',
    enKeyShift: 'B',
    ruKeyShift: 'И',
    ruKey: 'и',
    enKeyCaps: 'B',
    ruKeyCaps: 'И',
    id: 47,
  },
  48: {
    enKey: 'n',
    enKeyShift: 'N',
    ruKeyShift: 'Т',
    ruKey: 'т',
    enKeyCaps: 'N',
    ruKeyCaps: 'Т',
    id: 48,
  },
  49: {
    enKey: 'm',
    enKeyShift: 'M',
    ruKeyShift: 'Ь',
    ruKey: 'ь',
    enKeyCaps: 'M',
    ruKeyCaps: 'Ь',
    id: 49,
  },
  50: {
    enKey: ',',
    enKeyShift: '<',
    ruKeyShift: 'Б',
    ruKey: 'б',
    enKeyCaps: ',',
    ruKeyCaps: 'Б',
    id: 50,
  },
  51: {
    enKey: '.',
    enKeyShift: '>',
    ruKeyShift: 'Ю',
    ruKey: 'ю',
    enKeyCaps: '.',
    ruKeyCaps: 'Ю',
    id: 51,
  },
  52: {
    enKey: '/',
    enKeyShift: '?',
    ruKeyShift: ',',
    ruKey: '.',
    enKeyCaps: '/',
    ruKeyCaps: '.',
    id: 52,
  },
  53: {
    enKey: String.fromCharCode(9650),
    id: 53,
    style: 'static',
  },
  54: {
    enKey: 'Shift',
    id: 54,
    style: 'static_mid',
  },
  55: {
    enKey: 'Ctrl',
    id: 55,
    style: 'static',
  },
  56: {
    enKey: 'Win',
    id: 56,
    style: 'static',
  },
  57: {
    enKey: 'Alt',
    id: 57,
    style: 'static',
  },
  58: {
    enKey: ' ',
    id: 58,
    style: 'space',
  },
  59: {
    enKey: 'Alt',
    id: 59,
    style: 'static',
  },
  60: {
    enKey: String.fromCharCode(9668),
    id: 60,
    style: 'static',
  },
  61: {
    enKey: String.fromCharCode(9660),
    id: 61,
    style: 'static',
  },
  62: {
    enKey: String.fromCharCode(9658),
    id: 62,
    style: 'static',
  },
  63: {
    enKey: 'Ctrl',
    id: 63,
    style: 'static',
  },
}

// let i = 0

// document.addEventListener('keydown', function (e) {
//   if (keyEvents[e.code]) {
//     keyEvents[e.code].id = i
//     i++
//     console.log(keyEvents)
//   }
// })
export const keyCodes = [
  'Backquote',
  'Digit1',
  'Digit2',
  'Digit3',
  'Digit4',
  'Digit5',
  'Digit6',
  'Digit7',
  'Digit8',
  'Digit9',
  'Digit0',
  'Minus',
  'Equal',
  'Backspace',
  'Tab',
  'KeyQ',
  'KeyW',
  'KeyE',
  'KeyR',
  'KeyT',
  'KeyY',
  'KeyU',
  'KeyI',
  'KeyO',
  'KeyP',
  'BracketLeft',
  'BracketRight',
  'Backslash',
  'Delete',
  'CapsLock',
  'KeyA',
  'KeyS',
  'KeyD',
  'KeyF',
  'KeyG',
  'KeyH',
  'KeyJ',
  'KeyK',
  'KeyL',
  'Semicolon',
  'Quote',
  'Enter',
  'ShiftLeft',
  'KeyZ',
  'KeyX',
  'KeyC',
  'KeyV',
  'KeyB',
  'KeyN',
  'KeyM',
  'Comma',
  'Period',
  'Slash',
  'ArrowUp',
  'ShiftRight',
  'ControlLeft',
  'MetaLeft',
  'AltLeft',
  'Space',
  'AltRight',
  'ArrowLeft',
  'ArrowDown',
  'ArrowRight',
  'ControlRight',
]
